url: http://sametdemir.xyz/
baseurl: "/"
title: Samet Demir
description: Computer Engineering Student, Undergraduate Research Assistant & Software Developer

twitter_username: simitii
github_username:  simitii
linkedin_username: simitii

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag