baseurl: "/"
title: Samet Demir
description: "PhD Student\nin Computer Science and Engineering\nat Koç University\n-\nMachine Learning Researcher"

twitter_username: simitii
github_username:  simitii
linkedin_username: simitii

social:
  name: Samet Demir
  links:
    - https://twitter.com/simitii
    - https://www.linkedin.com/in/simitii
    - https://github.com/simitii

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
